<a href="https://colab.research.google.com/github/Muppidathe/data-analysis/blob/main/DA_E1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#it is an inbuilt variable used to return current version of numpy package.
np.__version__

'1.26.4'

In [ ]:
#array() is an inbuilt function used to create arrays.
l=[10,20,30,40,60]
print(type(l))
a=np.array(l)
print(a)
type(a)

<class 'list'>
[10 20 30 40 60]


numpy.ndarray

In [ ]:
arr=np.array([10,700,890,3+4j,'hii',{'a':100,'b':200}])
arr

array([10, 700, 890, (3+4j), 'hii', {'a': 100, 'b': 200}], dtype=object)

In [ ]:
#dtype is an inbuilt var which is used to check the data type of individual element in an array.
arr1=np.array([100,True,4.56,4+5j,'hi',{1,2,3}])
print(arr1)
arr1.dtype

len(arr1)

[100 True 4.56 (4+5j) 'hi' {1, 2, 3}]


6

In [ ]:
#uni dim array
arr1=np.array([100,True,4.56,4+5j,'hi',{1,2,3}])
arr1

array([100, True, 4.56, (4+5j), 'hi', {1, 2, 3}], dtype=object)

In [ ]:
#bi dim array
a=[[1,2,3],
   [4,5,6]]

b=np.array(a)

In [ ]:
#multi dim array
l=[[[1,2,3],
    [10,11,12],
    [89,90,78]]]
c=np.array(l)

In [ ]:
arr1.ndim
b.ndim
c.ndim

3

In [ ]:
a=[10,4.56,789,90+3j,'100',{1,2,3},{'a':100}]
arr=np.array(a)
print(arr)
arr.dtype

[10 4.56 789 (90+3j) '100' {1, 2, 3} {'a': 100}]


dtype('O')

In [ ]:
#uni
a=np.array([12,5.6,78,900])
print(a)
a.ndim

[ 12.    5.6  78.  900. ]


1

In [ ]:
#bi dim
b=np.array()