<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/numpy_slicing_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
three_d=np.random.randint(0,101,size=(3,3))
three_d

array([[ 47,  47,   6],
       [ 97,  18,   6],
       [ 84,  13, 100]])

# ***Indexing***

In [4]:
three_d[0][0]

47

In [5]:
three_d[0,0]

47

In [15]:
three_d.item(0,1)

47

In [21]:
np.take(three_d,[1,2,6])

array([47,  6, 84])

# ***Slicing***

In [10]:
#first row
#three_d[row,column]
three_d[0,0:3]

array([47, 47,  6])

In [9]:
#first column
three_d[0:3,0]

array([47, 97, 84])

# array filtering

In [24]:
three_d[(three_d%2==0) & (three_d>6)]

array([ 18,  84, 100])

# ***Array Reshaping***

In [29]:
a=np.arange(1,10)
print("before reshaping ",a)
a=a.reshape(3,3)
print("After reshaping ",a)

before reshaping  [1 2 3 4 5 6 7 8 9]
After reshaping  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# transpose

In [31]:
a.T
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [38]:
a.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# ***Sorting***

*   axis=0 → Across multiple 2D arrays
*   axis=1 → Across rows within each 2D array
*   axis=2 → Across columns within each 2D array



In [47]:
print("before sorting \n",three_d)
print()
three_d.sort(axis=0)
three_d

before sorting 
 [[ 47  47   6]
 [ 97  18   6]
 [ 84  13 100]]



array([[ 47,  13,   6],
       [ 84,  18,   6],
       [ 97,  47, 100]])

# ***Stacking***

In [49]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [51]:
np.column_stack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [50]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [53]:
np.row_stack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])