<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/numpy_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
a+1

array([2, 3, 4])

In [4]:
b=np.full(shape=(3),fill_value=2)
a+b

array([3, 4, 5])

In [14]:
c=np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]],
             [[10,11,12],
              [13,14,15],
               [16,17,18]]])
c.shape

(2, 3, 3)

## sum()

In [17]:
c.sum(axis=2)

array([[ 6, 15, 24],
       [33, 42, 51]])

## min()

In [18]:
c.min(axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## max()

In [19]:
c.max(axis=1)

array([[ 7,  8,  9],
       [16, 17, 18]])

#add()

In [20]:
np.add(a,b)

array([3, 4, 5])

## subract()

In [21]:
np.subtract(a,b)

array([-1,  0,  1])

## multiply()

In [22]:
np.multiply(a,b)

array([2, 4, 6])

## divide()

In [23]:
np.divide(a,b)

array([0.5, 1. , 1.5])

# remainder()

In [25]:
np.remainder(a,b)

array([1, 0, 1])

#matrix multiply()

In [27]:
np.matmul(a,b)

12

## dot product

In [28]:
np.dot(a,b)

12

## square root


In [29]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

#cube root


In [31]:
np.cbrt(a)

array([1.        , 1.25992105, 1.44224957])

#logarithm

In [36]:
np.log2(a)

array([0.       , 1.       , 1.5849625])

In [42]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125])

In [43]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

#exponential/power

In [44]:
power_value_for_2=np.log2(a)
np.exp2(power_value_for_2)

array([1., 2., 3.])

In [49]:
power_value_for_10=np.log10(a)
np.power(10,power_value_for_10)

array([1., 2., 3.])

In [47]:
power_value_for_e=np.log(a)
np.exp(power_value_for_e)

array([1., 2., 3.])

# ***Statistics***

##mean()

In [51]:
print(c)
np.mean(c,axis=1)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


array([[ 4.,  5.,  6.],
       [13., 14., 15.]])

##median()

In [52]:
np.median(c,axis=1)

array([[ 4.,  5.,  6.],
       [13., 14., 15.]])

## standard deviation

In [54]:
np.std(c,axis=1)

array([[2.44948974, 2.44948974, 2.44948974],
       [2.44948974, 2.44948974, 2.44948974]])

## percentile()

In [61]:
np.percentile(c,axis=1,q=50)

array([[ 4.,  5.,  6.],
       [13., 14., 15.]])