<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/numpy_slicing_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
three_d=np.random.randint(0,101,size=(3,3))
three_d

array([[91, 84, 11],
       [89, 18, 91],
       [41, 31, 26]])

# ***Indexing***

In [3]:
three_d[0][0]

91

In [4]:
three_d[0,0]

91

In [5]:
three_d.item(0,1)

84

In [6]:
np.take(three_d,[1,2,6])

array([84, 11, 41])

# ***Slicing***

In [7]:
#first row
#three_d[row,column]
three_d[0,0:3]

array([91, 84, 11])

In [8]:
#first column
three_d[0:3,0]

array([91, 89, 41])

# array filtering

In [9]:
three_d[(three_d%2==0) & (three_d>6)]

array([84, 18, 26])

In [10]:
#return index
np.where(three_d%2==0)

(array([0, 1, 2]), array([1, 1, 2]))

# ***Array Reshaping***

In [11]:
a=np.arange(1,10)
print("before reshaping ",a)
a=a.reshape(3,3)
print("After reshaping ",a)

before reshaping  [1 2 3 4 5 6 7 8 9]
After reshaping  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# transpose

In [13]:
a.T
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [14]:
a.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# ***Sorting***

*   axis=0 → Across multiple 2D arrays
*   axis=1 → Across rows within each 2D array
*   axis=2 → Across columns within each 2D array



In [15]:
print("before sorting \n",three_d)
print()
three_d.sort(axis=0)
three_d

before sorting 
 [[91 84 11]
 [89 18 91]
 [41 31 26]]



array([[41, 18, 11],
       [89, 31, 26],
       [91, 84, 91]])

# ***Stacking***

In [16]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
np.column_stack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [18]:
np.vstack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
np.row_stack((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
np.concatenate((arr1,arr2),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [21]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])