<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/numpy_array_creation_datatype_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# <center>array creation</center>

In [6]:
one_d=np.array([1,2,3])
print(type(one_d))
one_d

<class 'numpy.ndarray'>


array([1, 2, 3])

In [66]:
two_d=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float16)
two_d

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float16)

In [10]:
#auto ndim set
three_d=np.array([1,2,3,4],ndmin=3)
three_d

array([[[1, 2, 3, 4]]])

# **Zero One Empty Fill Full Eye Diag**

In [16]:
#one_d_zero=np.zeros(shape=3)
two_d_zero=np.zeros(shape=(3,3))
two_d_zero


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#one_d_ones=np.ones(shape=3)
two_d_ones=np.ones(shape=(3,3))
two_d_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
#one_d_empty=np.empty(shape=3)
two_d_empty=np.empty(shape=(3,3))
two_d_empty

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#one_d_full=np.full(shape=3,fill_value=5)
two_d_full=np.full(shape=(3,3),fill_value=8,dtype=int)
two_d_full

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [27]:
two_d_empty=np.empty(shape=(3,3))
two_d_empty.fill(6.5)
two_d_empty

array([[6.5, 6.5, 6.5],
       [6.5, 6.5, 6.5],
       [6.5, 6.5, 6.5]])

In [28]:
np.eye(N=3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [36]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# **Random values**

In [38]:
#0 t0 1 (uniform distribution)
np.random.rand(2,2)

array([[0.25938257, 0.22447008],
       [0.48780839, 0.69385142]])

In [37]:
#mean of 0 and variance of 1
np.random.randn(2,2)

array([[ 0.80287192, -0.7234417 ],
       [ 1.87237716,  0.54127853]])

In [55]:
#from starting point to (ending-1) point
np.random.randint(2,10,size=(2,2))

array([[7, 2],
       [6, 7]])

# **range of values**

In [57]:
np.arange(start=2,stop=10,step=2)

array([2, 4, 6, 8])

In [58]:
np.linspace(start=2,stop=10,num=5)

array([ 2.,  4.,  6.,  8., 10.])

# ***data type conversion***

In [74]:
float_type=np.array([[1,2,3,4],[5,6,7,8]],dtype=np.float64)
int_type=float_type.astype(np.int32)
int_type

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)