<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/torch_tensor_creation_datatype_conversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as t

# tensor creation

In [13]:
t.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [31]:
t.tensor([[1,2,3],[4,5,6]],dtype=t.float16)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float16)

# empty zeros ones full fill eye

In [2]:
t.empty(2,2)

tensor([[-3.0701e+27,  4.4602e-41],
        [-3.1146e+27,  4.4602e-41]])

In [4]:
t.ones(2,3,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
t.zeros(4)

tensor([0., 0., 0., 0.])

In [7]:
a=t.full(size=(2,2),fill_value=5,dtype=t.float64)
a

tensor([[5., 5.],
        [5., 5.]], dtype=torch.float64)

In [9]:
t.fill(a,18)

tensor([[18., 18.],
        [18., 18.]], dtype=torch.float64)

In [10]:
t.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
t

tensor([[0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

# random

In [14]:
t.rand(2,2)

tensor([[0.1023, 0.9120],
        [0.3631, 0.6131]])

In [21]:
t.randn(2,3)

tensor([[ 0.7052, -0.9090, -1.1100],
        [-1.3806,  0.7618,  0.5154]])

In [22]:
t.randint(low=0,high=10,size=(2,2))

tensor([[4, 4],
        [8, 3]])

# range and linspace

In [23]:
t.arange(start=0,end=10,step=1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
t.linspace(start=0,end=10,steps=10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

# type conversion

In [30]:
int64=t.tensor([1,2,3],dtype=t.int64)
int32=int64.to(dtype=t.int32)
int32

tensor([1, 2, 3], dtype=torch.int32)