<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/torch_slicing_sorting_reshape_stacking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as t

In [2]:
a=t.tensor([1,2,3])
b=t.tensor([[4,5,6],[7,8,9]])

# indexing

In [3]:
a[0]

tensor(1)

In [4]:
b[0][0]

tensor(4)

In [6]:
b[0,0]

tensor(4)

# slicing

In [7]:
b[0,:]

tensor([4, 5, 6])

In [8]:
b[:,0]

tensor([4, 7])

# tensor filtering

In [15]:
b[(b%2==0) & (b<20)]

tensor([4, 6, 8])

In [17]:
t.where(a%2==0)

(tensor([1]),)

# reshapping

In [12]:
b.reshape(3,2)

tensor([[4, 5],
        [6, 7],
        [8, 9]])

In [13]:
b.flatten()

tensor([4, 5, 6, 7, 8, 9])

# tensor transpose

In [11]:
b.T

tensor([[4, 7],
        [5, 8],
        [6, 9]])

# sorting

In [20]:
b.sort(axis=1,descending=True)

torch.return_types.sort(
values=tensor([[6, 5, 4],
        [9, 8, 7]]),
indices=tensor([[2, 1, 0],
        [2, 1, 0]]))

# concatenation

In [21]:
tensor1=t.tensor([[1,2],[3,4]])
tensor2=t.tensor([[5,6],[7,8]])

In [22]:
t.concat([tensor1,tensor2],axis=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [23]:
t.vstack([tensor1,tensor2])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [24]:
t.row_stack([tensor1,tensor2])

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [25]:
t.concat([tensor1,tensor2],axis=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [26]:
t.hstack([tensor1,tensor2])

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

In [28]:
t.column_stack([tensor1,tensor2])

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])