<a href="https://colab.research.google.com/github/Muppidathe/numpy_pandas_torch/blob/main/torch_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as t

In [5]:
a=t.tensor([1,2,3])
b=t.tensor([4,5,6])

# add

In [6]:
a+b

tensor([5, 7, 9])

In [7]:
t.add(a,b)

tensor([5, 7, 9])

# subtract

In [8]:
a-b

tensor([-3, -3, -3])

In [12]:
t.subtract(a,b)

tensor([-3, -3, -3])

# multiply

In [10]:
a*b

tensor([ 4, 10, 18])

In [11]:
t.multiply(a,b)

tensor([ 4, 10, 18])

# divide

In [13]:
a/b

tensor([0.2500, 0.4000, 0.5000])

In [14]:
t.divide(a,b)

tensor([0.2500, 0.4000, 0.5000])

# remainder

In [15]:
a%b

tensor([1, 2, 3])

In [16]:
t.remainder(a,b)

tensor([1, 2, 3])

# sqrt()


In [19]:
t.sqrt(a)

tensor([1.0000, 1.4142, 1.7321])

# logarithm

In [21]:
t.log2(a)

tensor([0.0000, 1.0000, 1.5850])

In [22]:
t.log10(a)

tensor([0.0000, 0.3010, 0.4771])

In [23]:
t.log(a)

tensor([0.0000, 0.6931, 1.0986])

# exponetial

In [26]:
t.exp2(t.tensor([0.0000, 1.0000, 1.5850]))

tensor([1.0000, 2.0000, 3.0001])

In [28]:
t.pow(10,t.tensor([0.0000, 0.3010, 0.4771]))

tensor([1.0000, 1.9999, 2.9999])

In [29]:
t.exp(t.tensor([0.0000, 0.6931, 1.0986]))

tensor([1.0000, 1.9999, 3.0000])

#dot/matrix multiply

In [17]:
t.dot(a,b)

tensor(32)

In [18]:
t.matmul(a,b)

tensor(32)

# ***statistics***

### mean

In [42]:
t.mean(b)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [34]:
t.mean(b.to(dtype=t.float16))

tensor(5., dtype=torch.float16)

##median

In [32]:
t.median(a)

tensor(2)

### standart deviation

In [40]:
t.std(a.to(dtype=t.float16))

tensor(1., dtype=torch.float16)

# sum()

In [36]:
t.sum(a,axis=0)

tensor(6)

# min()

In [37]:
t.min(a)

tensor(1)

# max()

In [38]:
t.max(a)

tensor(3)